### ISSUE TITLE
[BFS] 석유 시추 문제

### ISSUE THREAD

**Issue by stopmin** [stopmin/Algorithmic-Problem-Solving-Strategies#1]
## ✏️ 문제
https://school.programmers.co.kr/learn/courses/30/lessons/250136

- bfs로 풀어야 할 것 같은데 생각보다 잘 안풀림 ㅠ
- 이거 풀면 bfs 이해할 수 있을 것 같아서 태윤이도 풀어봤으면 좋겠음!!

**Comment by pykido** [comment]
풀었습니다-! 블로그에 풀이도 남겼으니 참고해주세용~!
