### ISSUE TITLE
[문제추천] 오랜만에 DFS + BFS 문제 풀어봄은 어떤지~~

### ISSUE THREAD

**Issue by stopmin** [stopmin/Algorithmic-Problem-Solving-Strategies#3]
## 📝 문제
> 감잡는 문제와 실제 적용한 문제!!
- 제목: 1260번: DFS와 BFS
- 링크: https://www.acmicpc.net/problem/1260
- 제목: 5014번: 스타트링크
- 링크: https://www.acmicpc.net/problem/5014

## ✔️ 추천 이유
- 그동안 그래프에 소홀했던 것 같네욤 ㅜㅜ 레츠고!!! 4월 2주차 전까지 풀어봅시다 🔥🔥 

## 🧑‍💻 완료자
- [x] 지민 
- [x] 태윤

**Comment by stopmin** [comment]
@pykido 지민 현재 1260번은 완료했습니당 ㅎ

**Comment by stopmin** [comment]
@pykido 태윤 근데 5014번은 같이 풀이 비교해봐도 재밌을듯?? 지금 풀어보고 있는데 이거 bfs로 꼭 안풀어도 풀릴거같기도 하고.. 나중에 풀이법 공유 부탁 ㅎ

**Comment by stopmin** [comment]
**🔥 꼭 문제 풀고 보시오!!!**
- [괜찮아보이는 코드](https://www.acmicpc.net/source/76498623)

이 분 코드 좋은듯..!!! 나는 BFS를 큐를 두개를 써서 했는데 (현재 층 / 다음층으로 2개) 저렇게 풀면 큐 하나로도 해결되고 굳이 숫자를 안세어도 해결이 바로 되는 것 같아!! 또 층을 기준으로 list를 만들어둬서 **그 리스트에 해당 층수를 몇 번이동해서 도착할 수 있었는지 저장해두는거**.. 이거 진짜 좋은 것 같네 ㅠㅠㅠ 그렇게 하니깐 따로 queue를 나처럼 하나 더 안둬도 해결할 수 있는 것 같아!!! 


결국에 해당 층수에 대한 정보를 리스트로 갱신해두니 따로 몇번 이동했는지(graph depth) 세어볼 필요가 없어짐으로 더 간단하고 더 직관적인 방법이 될 수 있었던 것 같아.

하핫 다음에 이런식으로 graph depth가 중요한 bfs문제가 있다면 이런식으로 해결하면 될 것 같앙!!!

**Comment by pykido** [comment]
완료하였습니다-! 어 뭐야 너가 괜찮아보이는 코드 나랑 코드 짠 거 완전 똑같아서 놀람 ㄷㄷ;;
